/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityBar: typeof import('./src/components/layout/ActivityBar.vue')['default']
    AdvancedEditor: typeof import('./src/components/editor/AdvancedEditor.vue')['default']
    CodeStatistics: typeof import('./src/components/common/CodeStatistics.vue')['default']
    ConfigEditor: typeof import('./src/components/editor/ConfigEditor.vue')['default']
    ConfigView: typeof import('./src/components/sidebar/ConfigView.vue')['default']
    DrlEditor: typeof import('./src/components/DrlEditor.vue')['default']
    EditorGroup: typeof import('./src/components/layout/EditorGroup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSegmentedItem: typeof import('element-plus/es')['ElSegmentedItem']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExplorerView: typeof import('./src/components/sidebar/ExplorerView.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog.vue')['default']
    OutputPanel: typeof import('./src/components/panel/OutputPanel.vue')['default']
    Panel: typeof import('./src/components/layout/Panel.vue')['default']
    PreviewDialog: typeof import('./src/components/PreviewDialog.vue')['default']
    PreviewEditor: typeof import('./src/components/editor/PreviewEditor.vue')['default']
    PreviewView: typeof import('./src/components/sidebar/PreviewView.vue')['default']
    ProblemsPanel: typeof import('./src/components/panel/ProblemsPanel.vue')['default']
    Resizer: typeof import('./src/components/layout/Resizer.vue')['default']
    RuleActionBuilder: typeof import('./src/components/RuleActionBuilder.vue')['default']
    RuleConditionBuilder: typeof import('./src/components/RuleConditionBuilder.vue')['default']
    RuleEditor: typeof import('./src/components/editor/RuleEditor.vue')['default']
    RuleFlow: typeof import('./src/components/RuleFlow.vue')['default']
    RulesListView: typeof import('./src/components/sidebar/RulesListView.vue')['default']
    SearchView: typeof import('./src/components/sidebar/SearchView.vue')['default']
    SectionTitle: typeof import('./src/components/common/SectionTitle.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TerminalPanel: typeof import('./src/components/panel/TerminalPanel.vue')['default']
    VSCodeLayout: typeof import('./src/components/layout/VSCodeLayout.vue')['default']
  }
}
