<script setup lang="ts">
import { watch } from 'vue'
import { AlertTriangle } from 'lucide-vue-next'
import { useEditorState } from '@/composables/useEditorState'

const editorState = useEditorState()

// 当切换到高级模式标签页时，同步表单数据到编辑器
watch(
  () => editorState.advancedMode.value,
  (isAdvanced) => {
    if (isAdvanced) {
      // 切换到高级模式时，总是同步最新的表单数据到编辑器
      editorState.manualDrlCode.value = editorState.autoGeneratedCode.value
    }
  },
  { immediate: true }
)
</script>

<template>
  <div class="advanced-editor p-6">
    <div class="space-y-4">
      <!-- 代码编辑区 -->
      <div>
        <el-scrollbar max-height="calc(100vh - 300px)" class="bg-gray-50 border-2 border-gray-300 rounded-lg shadow-lg overflow-hidden">
          <el-input
            v-model="editorState.manualDrlCode.value"
            type="textarea"
            :autosize="{ minRows: 35 }"
            placeholder="在此手动编辑 DRL 规则代码..."
            style="font-family: 'Consolas', 'Monaco', 'Courier New', monospace; font-size: 14px; line-height: 1.6;"
            class="drl-editor-advanced"
            resize="none"
          />
        </el-scrollbar>
        <div class="mt-3 flex items-center gap-3 text-sm text-orange-700 bg-linear-to-r from-orange-50 to-yellow-50 border-l-4 border-orange-500 rounded-lg p-3 shadow-sm">
          <AlertTriangle :size="20" class="shrink-0 mt-0.5 text-orange-600" />
          <div>
            <p class="font-semibold mb-1">高级模式提示</p>
            <p class="text-xs text-gray-700 leading-relaxed">您正在直接编辑 DRL 代码。修改将影响下载和复制的结果，但不会保存到表单。切换到其他标签页时，高级模式中的修改将被丢弃，表单内容保持不变。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* 高级编辑器样式优化 */
:deep(.drl-editor-advanced .el-textarea__inner) {
  background: #ffffff !important;
  color: #1e293b !important;
  border: 1px solid #e2e8f0 !important;
  padding: 1rem !important;
  font-size: 14px !important;
  line-height: 1.7 !important;
  box-shadow: none !important;
}

:deep(.drl-editor-advanced .el-textarea__inner:focus) {
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.3) !important;
  border-color: #3b82f6 !important;
}
</style>
