<script setup lang="ts">
import { computed } from 'vue'
import { useEditorState } from '@/composables/useEditorState'
import PreviewDialog from '../PreviewDialog.vue'

const editorState = useEditorState()

// 生成 DRL 代码
const generateDRL = (): string => {
  if (editorState.advancedMode.value) {
    return editorState.manualDrlCode.value
  }
  return editorState.autoGeneratedCode.value
}

// 计算规则统计
const rulesCount = computed(() => editorState.rules.value.length)
const enabledRulesCount = computed(() => editorState.rules.value.filter(r => r.enabled).length)
</script>

<template>
  <div class="preview-editor p-6">
    <PreviewDialog
      :code="generateDRL()"
      :rules-count="rulesCount"
      :enabled-rules-count="enabledRulesCount"
    />
  </div>
</template>

<style scoped>
</style>
