<script setup lang="ts">
import { computed } from 'vue'
import { useEditorStore } from '@/stores/editorStore'
import PreviewDialog from '../PreviewDialog.vue'

const editorStore = useEditorStore()

// 生成 DRL 代码
const generateDRL = (): string => {
  if (editorStore.advancedMode) {
    return editorStore.manualDrlCode
  }
  return editorStore.autoGeneratedCode
}

// 计算规则统计
const rulesCount = computed(() => editorStore.rules.length)
const enabledRulesCount = computed(() => editorStore.rules.filter(r => r.enabled).length)
</script>

<template>
  <div class="preview-editor p-6">
    <PreviewDialog
      :code="generateDRL()"
      :rules-count="rulesCount"
      :enabled-rules-count="enabledRulesCount"
    />
  </div>
</template>

<style scoped>
</style>
