<script setup lang="ts">
import { computed, watch } from 'vue'
import {
  Tag,
  Settings,
  Target,
  Search,
  Zap,
  Wand2,
  Power,
  RotateCcw,
  Lock
} from 'lucide-vue-next'
import { useEditorState } from '@/composables/useEditorState'
import RuleConditionBuilder from '../RuleConditionBuilder.vue'
import RuleActionBuilder from '../RuleActionBuilder.vue'

interface Props {
  data?: {
    index?: number
  }
}

const props = defineProps<Props>()
const editorState = useEditorState()

// 当前编辑的规则
const rule = computed(() => {
  const index = props.data?.index
  if (index !== undefined && index >= 0 && index < editorState.rules.value.length) {
    return editorState.rules.value[index]
  }
  return null
})

// 监听切换到高级模式标签页时，同步表单数据到编辑器
watch(
  () => editorState.advancedMode.value,
  (isAdvanced) => {
    if (isAdvanced && rule.value) {
      // 当切换到高级模式时，同步最新的表单数据
      editorState.manualDrlCode.value = editorState.autoGeneratedCode.value
    }
  }
)

// 如果没有规则，显示提示
if (!rule.value) {
  // 可以在模板中显示提示
}
</script>

<template>
  <div class="rule-editor p-6">
    <template v-if="rule">
      <el-form :model="rule" label-width="120px" label-position="left" class="space-y-4">
        <!-- <el-form-item>
          <template #label>
            <div class="flex items-center gap-2">
              <Tag :size="16" class="text-indigo-600" />
              <span>规则名称</span>
            </div>
          </template>
          <el-input v-model="rule.name" maxlength="50" show-word-limit placeholder="输入规则名称">
          </el-input>
        </el-form-item> -->

        <el-form-item>
          <template #label>
            <div class="flex items-center gap-2">
              <Settings :size="16" class="text-teal-600" />
              <span>规则配置</span>
            </div>
          </template>
          <div class="flex flex-wrap gap-4 p-2 rounded-lg border border-green-400 w-full">
            <el-checkbox v-model="rule.enabled" size="large" class="cb-enabled hover:bg-white px-3 py-2 rounded transition-colors">
              <span class="inline-flex items-center gap-2">
                <Power :size="16" :class="rule.enabled ? 'text-green-600' : 'text-gray-400'" />
                <span class="text-sm font-medium">启用规则</span>
              </span>
            </el-checkbox>
            <el-checkbox v-model="rule.noLoop" size="large" class="cb-noloop hover:bg-white px-3 py-2 rounded transition-colors">
              <span class="inline-flex items-center gap-2">
                <RotateCcw :size="16" :class="rule.noLoop ? 'text-orange-600' : 'text-gray-400'" />
                <span class="text-sm font-medium">防止循环</span>
              </span>
            </el-checkbox>
            <el-checkbox v-model="rule.lockOnActive" size="large" class="cb-lock hover:bg-white px-3 py-2 rounded transition-colors">
              <span class="inline-flex items-center gap-2">
                <Lock :size="16" :class="rule.lockOnActive ? 'text-purple-600' : 'text-gray-400'" />
                <span class="text-sm font-medium">锁定激活</span>
              </span>
            </el-checkbox>
          </div>
        </el-form-item>

        <el-form-item>
          <template #label>
            <div class="flex items-center gap-2">
              <Target :size="16" class="text-purple-600" />
              <span>优先级</span>
            </div>
          </template>
          <el-input-number v-model="rule.salience" :min="0" :max="999" :step="1"></el-input-number>
        </el-form-item>

        <el-divider />

        <!-- 可视化模式切换 -->
        <el-form-item label-width="250px">
          <template #label>
            <div class="flex items-center justify-between w-full">
              <div class="flex items-center gap-2">
                <Wand2 :size="16" class="text-violet-600" />
                <span>编辑模式</span>
              </div>
              <el-switch
                v-model="rule.visualMode"
                class="ml-4"
                active-text="可视化"
              />
            </div>
          </template>
        </el-form-item>

        <!-- 条件 (when) -->
        <el-form-item :label-width="rule.visualMode ? '0' : '100'">
          <template #label v-if="!rule.visualMode">
            <div class="flex items-center gap-2">
              <Search :size="16" class="text-cyan-600" />
              <span>条件</span>
            </div>
          </template>

          <!-- 可视化模式 -->
          <RuleConditionBuilder
            v-show="rule.visualMode"
            v-model="rule.when"
          />

          <!-- 代码模式 -->
          <el-input
            v-show="!rule.visualMode"
            v-model="rule.when"
            type="textarea"
            :rows="3"
            placeholder="例如: $p: Person($age: age >= 18)"
            style="font-family: 'Consolas', 'Monaco', 'Courier New', monospace;"
            size="large">
          </el-input>
        </el-form-item>

        <!-- 动作-->
        <el-form-item :label-width="rule.visualMode ? '0' : '100'">
          <template #label v-if="!rule.visualMode">
            <div class="flex items-center gap-2">
              <Zap :size="16" class="text-orange-600" />
              <span>动作</span>
            </div>
          </template>

          <!-- 可视化模式 -->
          <RuleActionBuilder
            v-show="rule.visualMode"
            v-model="rule.then"
            :when-condition="rule.when"
          />

          <!-- 代码模式 -->
          <el-input
            v-show="!rule.visualMode"
            v-model="rule.then"
            type="textarea"
            :rows="4"
            placeholder="例如: $p.setAdult(true); update($p);"
            style="font-family: 'Consolas', 'Monaco', 'Courier New', monospace;"
            size="large">
          </el-input>
        </el-form-item>
      </el-form>
    </template>

    <div v-else class="text-center py-12">
      <div class="text-gray-600">
        <p class="text-lg mb-2">规则不存在</p>
        <p class="text-sm">请从侧边栏选择一个规则进行编辑</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* Checkbox 配色定制（启用/循环/锁定） */
:deep(.cb-enabled .el-checkbox__input.is-checked .el-checkbox__inner) {
  background-color: #16a34a !important;
  border-color: #16a34a !important;
}
:deep(.cb-enabled .el-checkbox__inner:hover) {
  border-color: #16a34a !important;
}
:deep(.cb-enabled.is-checked .el-checkbox__label),
:deep(.cb-enabled .el-checkbox__input.is-checked + .el-checkbox__label) {
  color: #16a34a !important;
}

:deep(.cb-noloop .el-checkbox__input.is-checked .el-checkbox__inner) {
  background-color: #ea580c !important;
  border-color: #ea580c !important;
}
:deep(.cb-noloop .el-checkbox__inner:hover) {
  border-color: #ea580c !important;
}
:deep(.cb-noloop.is-checked .el-checkbox__label),
:deep(.cb-noloop .el-checkbox__input.is-checked + .el-checkbox__label) {
  color: #ea580c !important;
}

:deep(.cb-lock .el-checkbox__input.is-checked .el-checkbox__inner) {
  background-color: #7c3aed !important;
  border-color: #7c3aed !important;
}
:deep(.cb-lock .el-checkbox__inner:hover) {
  border-color: #7c3aed !important;
}
:deep(.cb-lock.is-checked .el-checkbox__label),
:deep(.cb-lock .el-checkbox__input.is-checked + .el-checkbox__label) {
  color: #7c3aed !important;
}
</style>
