<script setup lang="ts">
import { ref, computed } from 'vue'
import { ElMessageBox } from 'element-plus'
import ConfigEditor from '../editor/ConfigEditor.vue'
import RuleEditor from '../editor/RuleEditor.vue'
import AdvancedEditor from '../editor/AdvancedEditor.vue'
import PreviewEditor from '../editor/PreviewEditor.vue'
import { useEditorState } from '@/composables/useEditorState'

const editorState = useEditorState()

// 编辑器标签页类型
interface EditorTab {
  id: string
  type: 'config' | 'rule' | 'advanced' | 'preview'
  title: string
  component: any
  data?: any
  modified?: boolean
}

const tabs = ref<EditorTab[]>([])
const activeTabId = ref<string>('')

// 添加标签页
const addTab = (tab: Omit<EditorTab, 'id'>) => {
  const id = `${tab.type}-${Date.now()}`
  const newTab: EditorTab = {
    ...tab,
    id,
    modified: false
  }
  tabs.value.push(newTab)
  activeTabId.value = id
  return id
}

// 关闭标签页
const closeTab = async (id: string) => {
  const tab = tabs.value.find(t => t.id === id)

  // 如果是高级模式标签页，需要确认
  if (tab?.type === 'advanced') {
    try {
      await ElMessageBox.confirm(
        '您已退出高级模式。高级模式中的修改不会被保存，表单内容将保持不变。',
        '退出高级模式',
        {
          confirmButtonText: '确定退出',
          cancelButtonText: '取消',
          type: 'warning',
          distinguishCancelAndClose: true
        }
      )
      // 用户确认，关闭高级模式状态
      editorState.advancedMode.value = false
    } catch {
      // 用户取消，不关闭标签页
      return
    }
  }

  const index = tabs.value.findIndex(tab => tab.id === id)
  if (index !== -1) {
    tabs.value.splice(index, 1)
    // 如果关闭的是当前标签页，切换到上一个或下一个
    if (activeTabId.value === id) {
      if (tabs.value.length > 0) {
        activeTabId.value = tabs.value[Math.min(index, tabs.value.length - 1)]?.id || ''
      } else {
        activeTabId.value = ''
      }
    }
  }
}

// 切换标签页
const switchTab = async (id: string) => {
  const tab = tabs.value.find(t => t.id === id)

  // 如果从高级模式切换，需要确认
  const currentTab = tabs.value.find(t => t.id === activeTabId.value)
  if (currentTab?.type === 'advanced' && tab?.type !== 'advanced') {
    try {
      await ElMessageBox.confirm(
        '您已退出高级模式。高级模式中的修改不会被保存，表单内容将保持不变。',
        '退出高级模式',
        {
          confirmButtonText: '确定退出',
          cancelButtonText: '取消',
          type: 'warning',
          distinguishCancelAndClose: true
        }
      )
      // 用户确认，关闭高级模式状态，允许切换
      editorState.advancedMode.value = false
      activeTabId.value = id
    } catch {
      // 用户取消，不切换标签页
      return
    }
  } else {
    activeTabId.value = id
  }
}

// 当前活动标签页
const activeTab = computed(() => {
  return tabs.value.find(tab => tab.id === activeTabId.value)
})

// 提供编辑器操作方法
const openConfigEditor = () => {
  const existingTab = tabs.value.find(tab => tab.type === 'config')
  if (existingTab) {
    activeTabId.value = existingTab.id
    return existingTab.id
  }
  return addTab({
    type: 'config',
    title: '全局配置',
    component: ConfigEditor
  })
}

const openRuleEditor = (ruleIndex: number) => {
  const existingTab = tabs.value.find(tab => tab.type === 'rule' && tab.data?.index === ruleIndex)
  if (existingTab) {
    activeTabId.value = existingTab.id
    return existingTab.id
  }
  return addTab({
    type: 'rule',
    title: `规则 ${ruleIndex + 1}`,
    component: RuleEditor,
    data: { index: ruleIndex }
  })
}

const openAdvancedEditor = () => {
  const existingTab = tabs.value.find(tab => tab.type === 'advanced')
  if (existingTab) {
    activeTabId.value = existingTab.id
    return existingTab.id
  }
  // 设置高级模式状态
  editorState.advancedMode.value = true
  editorState.manualDrlCode.value = editorState.autoGeneratedCode.value
  return addTab({
    type: 'advanced',
    title: '高级模式',
    component: AdvancedEditor
  })
}

const openPreviewEditor = () => {
  const existingTab = tabs.value.find(tab => tab.type === 'preview')
  if (existingTab) {
    activeTabId.value = existingTab.id
    return existingTab.id
  }
  return addTab({
    type: 'preview',
    title: '代码预览',
    component: PreviewEditor
  })
}

// 暴露方法给父组件
defineExpose({
  openConfigEditor,
  openRuleEditor,
  openAdvancedEditor,
  openPreviewEditor,
  closeTab
})
</script>

<template>
  <div class="editor-group flex flex-col flex-1 overflow-hidden bg-white">
    <!-- 标签页栏 -->
    <div v-if="tabs.length > 0" class="tabs-bar flex items-center bg-gray-100 border-b border-gray-300 overflow-x-auto">
      <div
        v-for="tab in tabs"
        :key="tab.id"
        :class="[
          'tab-item flex items-center gap-2 px-4 py-2 cursor-pointer border-r border-gray-300 transition-colors',
          activeTabId === tab.id
            ? 'bg-white text-gray-900'
            : 'bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900'
        ]"
        @click="switchTab(tab.id)"
      >
        <span class="text-sm">{{ tab.title }}</span>
        <el-button
          v-if="tabs.length > 1"
          text
          circle
          size="small"
          class="ml-2 w-4 h-4 min-w-0 p-0 flex items-center justify-center hover:bg-gray-300"
          @click.stop="closeTab(tab.id)"
        >
          <span class="text-xs">×</span>
        </el-button>
      </div>
    </div>

    <!-- 编辑器内容区域 -->
    <div class="editor-content flex-1 overflow-auto">
      <component
        v-if="activeTab"
        :is="activeTab.component"
        :key="activeTab.id"
        :data="activeTab.data"
      />
      <div v-else class="h-full flex items-center justify-center text-gray-500">
        <div class="text-center">
          <p class="text-lg mb-2">欢迎使用 DRL 编辑器</p>
          <p class="text-sm">从侧边栏选择功能开始编辑</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.tabs-bar {
  min-height: 36px;
}

.tab-item {
  min-width: 120px;
  max-width: 300px;
}

.editor-content {
  background: #ffffff;
}
</style>

