<script setup lang="ts">
import { computed, inject } from 'vue'
import { Hash, CheckCircle, FileCode, ToggleRight, FolderTree, Search, ClipboardList, Settings, Eye, HelpCircle, Terminal, AlertCircle, FileText } from 'lucide-vue-next'
import { useEditorState } from '@/composables/useEditorState'

const layoutState = inject<{
  activeView: any
  activePanel: any
}>('layoutState')

// 使用编辑器状态
const editorState = useEditorState()

// 计算状态栏信息
const statusItems = computed(() => {
  const rulesCount = editorState.rules.value.length
  const enabledRulesCount = editorState.rules.value.filter(r => r.enabled).length
  const codeLines = editorState.advancedMode.value
    ? editorState.manualDrlCode.value.split('\n').length
    : editorState.autoGeneratedCode.value.split('\n').length

  return [
    { label: `规则: ${rulesCount}`, icon: Hash },
    { label: `启用: ${enabledRulesCount}`, icon: CheckCircle },
    { label: `代码行: ${codeLines}`, icon: FileCode },
    { label: editorState.autoImportMode.value ? '自动导入: 开启' : '自动导入: 关闭', icon: ToggleRight }
  ]
})

// 获取视图图标
const getViewIcon = (view: string) => {
  const iconMap: Record<string, any> = {
    explorer: FolderTree,
    search: Search,
    rules: ClipboardList,
    config: Settings,
    preview: Eye,
    help: HelpCircle
  }
  return iconMap[view] || null
}

// 获取面板图标
const getPanelIcon = (panel: string) => {
  const iconMap: Record<string, any> = {
    problems: AlertCircle,
    output: FileText,
    terminal: Terminal
  }
  return iconMap[panel] || null
}

// 当前视图图标
const activeViewIcon = computed(() => {
  const view = layoutState?.activeView?.value || 'rules'
  return getViewIcon(view)
})

// 当前面板图标
const activePanelIcon = computed(() => {
  const panel = layoutState?.activePanel?.value
  return panel ? getPanelIcon(panel) : null
})
</script>

<template>
  <div class="status-bar h-6 bg-blue-500 text-white flex items-center justify-between px-4 text-xs">
    <div class="flex items-center gap-4">
      <div
        v-for="(item, index) in statusItems"
        :key="index"
        class="flex items-center gap-1.5"
      >
        <component v-if="item.icon" :is="item.icon" :size="12" class="shrink-0" />
        <span>{{ item.label }}</span>
      </div>
    </div>

    <div class="flex items-center gap-4">
      <div class="flex items-center gap-1.5">
        <component v-if="activeViewIcon" :is="activeViewIcon" :size="12" class="shrink-0" />
        <span>{{ layoutState?.activeView?.value || 'rules' }}</span>
      </div>
      <div v-if="layoutState?.activePanel?.value" class="flex items-center gap-1.5">
        <component v-if="activePanelIcon" :is="activePanelIcon" :size="12" class="shrink-0" />
        <span>{{ layoutState.activePanel.value }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.status-bar {
  font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
  user-select: none;
}
</style>

