<script setup lang="ts">
import { computed, inject } from 'vue'
import { CheckCircle } from 'lucide-vue-next'
import { useEditorState } from '@/composables/useEditorState'

const layoutState = inject<{
  activeView: any
  activePanel: any
}>('layoutState')

// 使用编辑器状态
const editorState = useEditorState()

// 计算状态栏信息
const statusItems = computed(() => {
  const rulesCount = editorState.rules.value.length
  const enabledRulesCount = editorState.rules.value.filter(r => r.enabled).length
  const codeLines = editorState.advancedMode.value
    ? editorState.manualDrlCode.value.split('\n').length
    : editorState.autoGeneratedCode.value.split('\n').length

  return [
    { label: `规则: ${rulesCount}`, icon: null },
    { label: `启用: ${enabledRulesCount}`, icon: CheckCircle },
    { label: `代码行: ${codeLines}`, icon: null },
    { label: editorState.autoImportMode.value ? '自动导入: 开启' : '自动导入: 关闭', icon: null }
  ]
})
</script>

<template>
  <div class="status-bar h-6 bg-blue-600 text-white flex items-center justify-between px-4 text-xs">
    <div class="flex items-center gap-4">
      <div
        v-for="(item, index) in statusItems"
        :key="index"
        class="flex items-center gap-1"
      >
        <component v-if="item.icon" :is="item.icon" :size="12" />
        <span>{{ item.label }}</span>
      </div>
    </div>

    <div class="flex items-center gap-4">
      <span>{{ layoutState?.activeView?.value || 'rules' }}</span>
      <span v-if="layoutState?.activePanel?.value">{{ layoutState.activePanel.value }}</span>
    </div>
  </div>
</template>

<style scoped>
.status-bar {
  font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
  user-select: none;
}
</style>

