import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { generateDrlCode, formatTimestamp } from '@/utils/drl'
import { v4 as uuidv4 } from 'uuid'

export const useEditorStore = defineStore('editor', () => {
  // 状态
  const config = ref<Config>({
    package: '',
    imports: [],
    globals: [],
    description: ''
  })

  const rules = ref<Rule[]>([])
  const activeRules = ref<number | string>(0)
  const autoImportMode = ref(true)
  const advancedMode = ref(false)
  const manualDrlCode = ref('')
  const fixedDrlId = ref(uuidv4())
  const fixedTimestamp = ref(formatTimestamp())

  // 计算属性
  const autoGeneratedCode = computed(() => {
    return generateDrlCode(
      config.value.package,
      config.value.imports,
      config.value.globals,
      rules.value,
      config.value.description,
      fixedDrlId.value,
      fixedTimestamp.value
    )
  })

  // 操作方法
  const resetDrlId = () => {
    fixedDrlId.value = uuidv4()
    fixedTimestamp.value = formatTimestamp()
  }

  return {
    // 状态
    config,
    rules,
    activeRules,
    autoImportMode,
    advancedMode,
    manualDrlCode,
    fixedDrlId,
    fixedTimestamp,
    // 计算属性
    autoGeneratedCode,
    // 方法
    resetDrlId
  }
})

