<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Trash2, HelpCircle, Lightbulb, Download, Copy, Check, Plus } from 'lucide-vue-next'
import { useClipboard } from '@vueuse/core'
import HelpDialog from './HelpDialog.vue'
import SectionTitle from './SectionTitle.vue'
import { generateDrlCode, downloadFile, formatTimestamp } from '../utils/drl'
import { v4 as uuidv4 } from 'uuid'

// 数据定义
const config = ref<Config>({
  package: '',
  globals: [],
  description: ''
})

// 包名选项
const packageOptions = [
  { value: 'com.example.rules', label: 'com.example.rules (示例包)' },
  { value: 'com.company.drools.rules', label: 'com.company.drools.rules (公司规则包)' },
  { value: 'com.myapp.business.rules', label: 'com.myapp.business.rules (业务规则包)' },
  { value: 'org.example.rules', label: 'org.example.rules (组织规则包)' },
  { value: 'cn.example.rules', label: 'cn.example.rules (中文域名包)' }
]

// 全局变量选项
const globalOptions = [
  { value: 'global org.slf4j.Logger logger;', label: 'Logger (日志)' },
  { value: 'global java.util.Map dataMap;', label: 'Map (数据映射)' },
  { value: 'global java.util.List resultList;', label: 'List (结果列表)' },
  { value: 'global com.example.service.RuleService ruleService;', label: 'RuleService (规则服务)' },
  { value: 'global com.example.util.DateUtils dateUtils;', label: 'DateUtils (日期工具)' },
  { value: 'global com.example.util.StringUtils stringUtils;', label: 'StringUtils (字符串工具)' }
]

const rules = ref<Rule[]>([])
const activeRules = ref<number | string>(0)

// 控制折叠面板显示
const activeConfig = ref<string>('config') // 全局配置折叠状态
const activeRuleList = ref<string>('ruleList') // 规则列表折叠状态

// 控制帮助弹窗显示
const showHelpDialog = ref(false)

// 高级模式状态
const advancedMode = ref(false)
const manualDrlCode = ref('')

// 固定的文件ID和时间戳（在整个会话中保持不变）
const fixedDrlId = ref(uuidv4())
const fixedTimestamp = ref(formatTimestamp())

// 缓存自动生成的代码（使用固定的UUID，避免重复生成）
const autoGeneratedCode = computed(() => {
  return generateDrlCode(
    config.value.package,
    config.value.globals,
    rules.value,
    config.value.description,
    fixedDrlId.value,
    fixedTimestamp.value
  )
})

// 使用 VueUse 的 useClipboard (legacy 模式)
const { copy, copied, isSupported } = useClipboard({ legacy: true })

/**
 * 添加新规则
 */
const addRule = () => {
  rules.value.push({
    name: 'rule_' + Date.now(),
    enabled: true,
    salience: 10,
    noLoop: false,
    lockOnActive: false,
    when: '',
    then: ''
  })
  // 自动展开新添加的规则
  activeRules.value = rules.value.length - 1
}

/**
 * 确认删除规则
 */
const confirmRemoveRule = (index: number) => {
  // @ts-ignore
  const ruleName = rules.value[index].name || `规则 ${index + 1}`
  ElMessageBox.confirm(
    `确定要删除规则"${ruleName}"吗？此操作不可恢复。`,
    '删除确认',
    {
      confirmButtonText: '确定删除',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    removeRule(index)
    ElMessage({
      type: 'success',
      message: '规则已删除'
    })
  }).catch(() => {
    // 用户取消删除
  })
}

/**
 * 删除规则
 */
const removeRule = (index: number) => {
  rules.value.splice(index, 1)
  // 删除规则后调整 activeRules
  if (typeof activeRules.value === 'number' && activeRules.value >= rules.value.length && rules.value.length > 0) {
    activeRules.value = rules.value.length - 1
  } else if (rules.value.length === 0) {
    activeRules.value = -1
  }
}

/**
 * 加载示例规则
 */
const loadSample = () => {
  // 设置全局配置
  config.value = {
    package: 'com.example.rules',
    globals: ['global org.slf4j.Logger logger;'],
    description: '示例规则文件'
  }

  // 设置规则示例
  rules.value = [
    {
      name: 'CheckAdult',
      enabled: true,
      salience: 10,
      noLoop: true,
      lockOnActive: false,
      when: '    $p: Person($age: age >= 18)',
      then: '    $p.setAdult(true);\n    logger.info("{} 已成年",$p.getName());\n    update($p);'
    },
    {
      name: 'CheckSex',
      enabled: true,
      salience: 15,
      noLoop: false,
      lockOnActive: false,
      when: '    $p : Person(sex == "girl")',
      then: '    logger.warn("{} 是一个女孩", $p.getName());\n    $p.setSex("boy");\n    update($p);'
    }
  ]
  // 展开第一个规则
  activeRules.value = 0
}

/**
 * 生成 DRL 代码
 */
const generateDRL = (): string => {
  if (advancedMode.value) {
    return manualDrlCode.value
  }
  return autoGeneratedCode.value
}

/**
 * 处理高级模式切换
 */
const handleAdvancedModeChange = (value: string | number | boolean) => {
  if (value === true) {
    // 先恢复开关状态
    advancedMode.value = false

    // 弹出确认框
    ElMessageBox.confirm(
      '开启高级模式后，您可以直接编辑 DRL 代码。手动修改的内容将覆盖表单生成的代码，并影响下载和复制的结果。',
      '开启高级模式',
      {
        confirmButtonText: '确定开启',
        cancelButtonText: '取消',
        type: 'warning',
        distinguishCancelAndClose: true
      }
    ).then(() => {
      // 用户确认，使用当前预览中显示的代码（此时此刻的值，不会重新生成UUID）
      // 如果 manualDrlCode 为空，才从预览中获取
      if (!manualDrlCode.value) {
        // 获取当前autoGeneratedCode的值（包含已生成的UUID）
        manualDrlCode.value = autoGeneratedCode.value
      }
      // 然后开启高级模式
      advancedMode.value = true
      ElMessage({
        type: 'success',
        message: '已开启高级模式，可以手动编辑代码'
      })
    }).catch(() => {
      // 用户取消，保持关闭状态（已经是 false）
    })
  }
  // 注意：关闭高级模式时不清空 manualDrlCode，保留用户的编辑内容
}

/**
 * 下载 DRL 文件
 */
const downloadDRL = () => {
  const code = generateDRL()
  const filename = `rules-${Date.now()}.drl`
  downloadFile(code, filename)
}

/**
 * 复制代码到剪贴板
 */
const copyCode = async () => {
  if (!isSupported.value) {
    ElMessage.error('当前浏览器不支持复制功能')
    return
  }

  const code = generateDRL()
  await copy(code)

  if (copied.value) {
    ElMessage.success('复制成功！')
  } else {
    ElMessage.error('复制失败')
  }
}

// 组件挂载时初始化
onMounted(() => {
  // 初始化：添加第一个规则
  addRule()
  // 或者加载示例
  // loadSample()
})
</script>

<template>
  <div class="bg-linear-to-br from-slate-50 via-blue-50 to-slate-50 min-h-screen p-4">
    <div class="max-w-7xl mx-auto space-y-4">
      <!-- 标题 -->
      <div class="bg-white/90 backdrop-blur-sm rounded-lg shadow-sm p-4 border border-slate-200">
        <div class="flex flex-col md:flex-row md:items-center md:justify-between space-y-3 md:space-y-0">
          <div>
            <SectionTitle class="mt-0">
              DRL 规则编辑器
            </SectionTitle>
            <p class="text-sm text-gray-600">可视化生成 Drools 规则文件</p>
          </div>
          <div class="flex flex-wrap gap-2">
            <el-button
              class="bg-linear-to-br! from-blue-50! to-blue-100! text-blue-700! border! border-blue-200! hover:border-blue-300! hover:shadow-md! transition-all!"
              @click="showHelpDialog = true"
            >
              <HelpCircle :size="16" class="mr-1" />
              使用帮助
            </el-button>
            <el-button
              class="bg-linear-to-br! from-cyan-50! to-teal-100! text-teal-700! border! border-cyan-200! hover:border-teal-300! hover:shadow-md! transition-all!"
              @click="loadSample"
              :disabled="advancedMode"
            >
              <Lightbulb :size="16" class="mr-1" />
              加载示例
            </el-button>
            <el-button
              class="bg-linear-to-br! from-emerald-50! to-green-100! text-green-700! border! border-emerald-200! hover:border-green-300! hover:shadow-md! transition-all!"
              @click="downloadDRL"
            >
              <Download :size="16" class="mr-1" />
              下载 DRL 文件
            </el-button>
            <el-button
              :class="copied
                ? 'bg-linear-to-br! from-green-50! to-emerald-100! text-emerald-700! border! border-green-200! shadow-sm! transition-all!'
                : 'bg-linear-to-br! from-purple-50! to-indigo-100! text-indigo-700! border! border-purple-200! hover:border-indigo-300! hover:shadow-md! transition-all!'
              "
              @click="copyCode"
            >
              <Copy v-if="!copied" :size="16" class="mr-1" />
              <Check v-else :size="16" class="mr-1" />
              {{ copied ? '已复制！' : '复制代码' }}
            </el-button>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <!-- 左侧：规则配置表单 -->
        <div class="space-y-4 relative">
          <!-- 高级模式禁用提示 -->
          <div v-if="advancedMode" class="absolute inset-0 bg-slate-200/30 backdrop-blur-[1px] z-10 rounded-lg flex items-center justify-center">
            <div class="bg-red-500 text-white px-4 py-2 rounded-lg shadow-lg text-sm font-semibold">
              🔒 高级模式：表单已禁用
            </div>
          </div>
          <!-- 全局配置 -->
          <div class="bg-white/90 backdrop-blur-sm rounded-lg shadow-sm p-4 border border-slate-200">
            <el-collapse v-model="activeConfig" accordion>
              <el-collapse-item name="config">
                <template #title>
                  <SectionTitle class="mb-0">全局配置</SectionTitle>
                </template>
                <el-form :model="config" label-width="140px" label-position="top" :disabled="advancedMode" class="pt-2">
                  <el-form-item label="包名">
                    <el-select
                      v-model="config.package"
                      filterable
                      allow-create
                      default-first-option
                      placeholder="选择或输入包名"
                      class="w-full"
                    >
                      <el-option
                        v-for="item in packageOptions"
                        :key="item.value"
                        :label="item.label"
                        :value="item.value"
                      />
                    </el-select>
                  </el-form-item>
                  <el-form-item label="全局变量">
                    <el-select
                      v-model="config.globals"
                      multiple
                      placeholder="选择全局变量"
                      class="w-full"
                      collapse-tags
                      collapse-tags-tooltip
                      :max-collapse-tags="3"
                    >
                      <el-option
                        v-for="item in globalOptions"
                        :key="item.value"
                        :label="item.label"
                        :value="item.value"
                      />
                    </el-select>
                  </el-form-item>
                  <el-form-item label="描述">
                    <el-input
                      v-model="config.description"
                      type="textarea"
                      :rows="2"
                      placeholder="请输入规则文件的描述信息"
                      maxlength="200"
                      show-word-limit
                    />
                  </el-form-item>
                </el-form>
              </el-collapse-item>
            </el-collapse>
          </div>

          <!-- 规则列表 -->
          <div class="bg-white/90 backdrop-blur-sm rounded-lg shadow-sm p-4 border border-slate-200">
            <el-collapse v-model="activeRuleList" accordion>
              <el-collapse-item name="ruleList">
                <template #title>
                  <div class="flex justify-between items-center w-full pr-4">
                    <SectionTitle class="mb-0">规则列表</SectionTitle>
                    <el-button
                      class="mr-1 bg-linear-to-br! from-sky-50! to-blue-100! text-blue-700! border! border-sky-200! hover:border-blue-300! hover:shadow-md! transition-all!"
                      @click.stop="addRule"
                      :disabled="advancedMode"
                      size="small"
                    >
                      <Plus :size="16" class="mr-1" />
                      添加规则
                    </el-button>
                  </div>
                </template>
                <div class="pt-2">
                  <el-collapse v-model="activeRules" accordion>
                    <el-collapse-item v-for="(rule, index) in rules" :key="index" :name="index" :disabled="advancedMode">
                      <template #title>
                        <div class="flex items-center justify-between w-full pr-4 group">
                          <div class="flex items-center gap-3">
                            <span class="font-semibold text-gray-700">
                              {{ rule.name || '规则 ' + (index + 1) }}
                            </span>
                            <el-tag v-if="rule.enabled" class="bg-emerald-100! text-emerald-700! border-emerald-200! transition-none!">启用</el-tag>
                            <el-tag v-else class="bg-slate-100! text-slate-600! border-slate-200! transition-none!">禁用</el-tag>
                            <el-tag v-if="rule.salience > 0" class="bg-violet-100! text-violet-700! border-violet-200! transition-none!">优先级: {{ rule.salience }}</el-tag>
                          </div>
                            <Trash2 v-if="!advancedMode" :size="12" class="group-hover:opacity-100 opacity-0 transition-all duration-200 delay-250 text-red-400 mr-2" @click.stop="confirmRemoveRule(index)" />
                        </div>
                      </template>
                      <el-form :model="rule" label-width="120px" label-position="top" class="pt-2" :disabled="advancedMode">
                        <el-form-item label="规则名称">
                          <el-input v-model="rule.name" maxlength="25" show-word-limit placeholder="规则名称"></el-input>
                        </el-form-item>
                        <el-form-item label="规则选项">
                          <div class="grid grid-cols-3 gap-2">
                            <el-checkbox v-model="rule.enabled">启用</el-checkbox>
                            <el-checkbox v-model="rule.noLoop">循环</el-checkbox>
                            <el-checkbox v-model="rule.lockOnActive">锁定</el-checkbox>
                          </div>
                        </el-form-item>
                        <el-form-item label="优先级 (salience)">
                          <el-input-number v-model="rule.salience" :min="0" :max="999"></el-input-number>
                        </el-form-item>
                        <el-form-item label="条件">
                          <el-input
                            v-model="rule.when"
                            type="textarea"
                            :rows="2"
                            placeholder="例如: $p: Person($age: age >= 18)"
                            style="font-family: monospace;">
                          </el-input>
                        </el-form-item>
                        <el-form-item label="动作">
                          <el-input
                            v-model="rule.then"
                            type="textarea"
                            :rows="3"
                            placeholder="例如: $p.setAdult(true); update($p);"
                            style="font-family: monospace;">
                          </el-input>
                        </el-form-item>
                      </el-form>
                    </el-collapse-item>
                  </el-collapse>
                </div>
              </el-collapse-item>
            </el-collapse>
          </div>
        </div>

        <!-- 右侧：代码预览和帮助 -->
        <div class="space-y-4">
          <div class="bg-white/90 backdrop-blur-sm rounded-lg shadow-sm p-4 border border-slate-200">
            <div class="flex justify-between items-center mb-3">
              <SectionTitle class="mb-0">DRL 代码预览</SectionTitle>
              <div class="flex items-center gap-2">
                <span class="text-sm text-gray-600">高级模式</span>
                <el-switch
                  v-model="advancedMode"
                  active-color="#10b981"
                  inactive-color="#94a3b8"
                  @change="handleAdvancedModeChange"
                />
              </div>
            </div>

            <!-- 高级模式：可编辑 -->
            <div v-if="advancedMode">
              <el-scrollbar max-height="600px" class="bg-linear-to-br from-slate-50 to-slate-100 border-2! border-red-500! rounded shadow-inner">
                <el-input
                  v-model="manualDrlCode"
                  type="textarea"
                  :autosize="{ minRows: 28 }"
                  placeholder="在此手动编辑 DRL 规则代码..."
                  style="font-family: 'Consolas', 'Monaco', 'Courier New', monospace; font-size: 13px;"
                  class="drl-editor"
                  resize="none"
                />
              </el-scrollbar>
              <div class="mt-2 text-xs text-red-700 bg-red-50 border border-red-300 rounded p-2">
                ⚠️ 高级模式下，您可以直接编辑代码。左侧表单已被禁用，所有修改将通过代码编辑器进行。退出高级模式后将恢复为自动生成。
              </div>
            </div>

            <!-- 普通模式：只读预览 -->
            <el-scrollbar v-else max-height="600px" class="bg-linear-to-br from-slate-50 to-slate-100 border border-slate-300 rounded shadow-inner">
              <pre class="text-slate-800 p-4 text-sm font-mono min-h-[400px]">{{ generateDRL() }}</pre>
            </el-scrollbar>
          </div>
        </div>
      </div>
    </div>

    <!-- 帮助弹窗组件 -->
    <HelpDialog v-model="showHelpDialog" />
  </div>
</template>