import { ref, computed, provide, inject, type Ref, type ComputedRef } from 'vue'
import { generateDrlCode, formatTimestamp } from '@/utils/drl'
import { v4 as uuidv4 } from 'uuid'

// 全局状态键
const STATE_KEY = Symbol('drl-editor-state')

// 全局状态接口
interface DrlEditorState {
  config: Ref<Config>
  rules: Ref<Rule[]>
  activeRules: Ref<number | string>
  autoImportMode: Ref<boolean>
  advancedMode: Ref<boolean>
  manualDrlCode: Ref<string>
  fixedDrlId: Ref<string>
  fixedTimestamp: Ref<string>
  autoGeneratedCode: ComputedRef<string>
}

/**
 * 创建编辑器状态（应在根组件调用）
 */
export function createEditorState() {
  const config = ref<Config>({
    package: '',
    imports: [],
    globals: [],
    description: ''
  })

  const rules = ref<Rule[]>([])
  const activeRules = ref<number | string>(0)
  const autoImportMode = ref(true)
  const advancedMode = ref(false)
  const manualDrlCode = ref('')
  const fixedDrlId = ref(uuidv4())
  const fixedTimestamp = ref(formatTimestamp())

  // 自动生成的代码
  const autoGeneratedCode = computed(() => {
    return generateDrlCode(
      config.value.package,
      config.value.imports,
      config.value.globals,
      rules.value,
      config.value.description,
      fixedDrlId.value,
      fixedTimestamp.value
    )
  })

  const state: DrlEditorState = {
    config,
    rules,
    activeRules,
    autoImportMode,
    advancedMode,
    manualDrlCode,
    fixedDrlId,
    fixedTimestamp,
    autoGeneratedCode
  }

  provide(STATE_KEY, state)
  return state
}

/**
 * 使用编辑器状态（在子组件中使用）
 */
export function useEditorState(): DrlEditorState {
  const state = inject<DrlEditorState>(STATE_KEY)
  if (!state) {
    throw new Error('useEditorState must be used within a component that calls createEditorState')
  }
  return state
}

